### PR TITLE
Merging in a LOT of upstream changes from root winston

### PR DESCRIPTION
**Pull request by zbirkenbuel**
There are only a few changes we've made to winston.  This brings in all of the good work from main newton to our fork.

For easy compare, this is comparing my branch with winston master: https://github.com/winstonjs/winston/compare/master...HBOCodeLabs:zackb-massive

It effectively reflects the changes we made to winston relative to when we forked (which weren't that many)

### CODE REVIEW

**Comment by zbirkenbuel** [comment]
@joecastro @allenarthurgay @shimeez

**Comment by zbirkenbuel** [comment]
@jstamerj

**Comment by allenarthurgay** [comment]
The only place I can see these labels be provided are here: https://github.com/HBOCodeLabs/fitass/blob/master/src/logManager.coffee

Am i following this right?

**Comment by zbirkenbuel** [comment]
@allenarthurgay yep, but those are defaults, applied to all instances everywhere

**Comment by jstamerj** [comment]
Nice.  Good to go!

**Pull request merged**
